apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-config-server-api-stage-dep
  #namespace: notif-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-config-server-api-stage-dep
  template:
    metadata:
      labels:
        app: spring-config-server-api-stage-dep
    spec:
      containers:
      - image: oeotstuscacr.azurecr.io/spring-config-server-api-stage:latest
        command: ["java","-Dspring.profiles.active=stage","-Xms2048m","-Xmx3072m","-Dlogging.file=/logs/spring-config-stage.log","-Dserver.port=8888","-jar","spring-config-server-api.jar"]
        name: spring-config-server-api-stage-dep
        env:
        - name: START_DELAY
          value: "0"        
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1"
          requests:
            memory: "1024Mi"
            cpu: "0.5"    
      imagePullSecrets:
        - name: oeo-acr-secret
