spring:
  application:
    name: config server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/greddy16/spring-cloud-config-server-properties
          clone-on-start: true

server:
  port: 8888