spring:
  application:
    name: config server
  cloud:
    config:
      server:
        git:
          uri: ${config-server-azure-git-uri}
          clone-on-start: true
          skip-ssl-validation: true
          username: ${config-server-azure-git-username}
          password: ${config-server-azure-git-password}
          search-paths: ${config-server-azure-git-folder-location}
azure:
  keyvault:
    client-id: ${keyvault-client-id}
    client-key: ${keyvault-client-key}
    uri: ${keyvault-uri}
server:
  port: 8888