spring:
  application:
    name: config server
  cloud:
    config:
      server:
        git:
          uri: ${config-server-azure-git-uri}
          clone-on-start: true
          skip-ssl-validation: true
          username: ${config-server-azure-git-username}
          password: ${config-server-azure-git-password}
          search-paths: ${config-server-azure-git-folder-location}

azure:
  keyvault:
    client-id: c606f0a4-ce8e-4c0d-9939-1365473e620d
    client-key: kxrT3.ZfX2DRHI5XvCS4.fAlmBjP-SoqGU
    uri: https://oeo-stg-us-c-kv.vault.azure.net/

server:
  port: 8888
