spring:
  application:
    name: config server
  cloud:
    config:
      server:
        git:
          uri: https://configserver@dev.azure.com/configserver/spring-cloud-config-server-properties/_git/spring-cloud-config-server-properties
          clone-on-start: true
          skip-ssl-validation: true
          username: configserver
          password: ngjvnekkdcoospwk6tyqbzoqp7ztnwycq5no4idw5l7dw5unx3ta

server:
  port: 8888