apiVersion: v1
kind: Service
metadata:
  name: spring-config-server-api-stage-east-svc
  #namespace: stage
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8888
  selector:
    app: spring-config-server-api-stage-east-dep
