apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: spring-config-server-api-prod-east-dep
  #namespace: onboarding
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-config-server-api-prod-east-dep
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
